'use strict';

/**
 * TRUST-04 / D-06 / D-07: the single-source drift tripwire + generator for the
 * dependency-free CommonJS write-gate copy.
 *
 * There is exactly ONE authored allowlist declaration in the repo (src/lib/trust.ts,
 * D-05). A GitHub JS action must decide write-trust BEFORE `npm ci` runs, so it
 * cannot import the compiled TS module -- it needs a committed, dependency-free
 * CommonJS copy. This script GENERATES that copy from trust.ts source (never a
 * hand-maintained dual copy) and, with no args, byte-diffs the committed copy to
 * fail CI on any drift (a hand edit, or a trust.ts change with no regeneration).
 *
 * It extracts the two allowlist arrays from the trust.ts SOURCE (not the dist
 * build output), so it is build-order-independent and runs with node builtins
 * only (A4 / T-05-04-03). Wired into ci.yml as its own job (D-07).
 *
 * Usage:
 *   node packages/github-cache/selfcheck.cjs           # regenerate + byte-diff; exit 1 on drift
 *   node packages/github-cache/selfcheck.cjs --write    # (re)write the committed .cjs
 *
 * ponytail: deterministic regex extraction of two n=2 array literals; an AST
 * parser would be more code for no gain at this shape.
 */

const fs = require('node:fs');
const path = require('node:path');

const TRUST_TS_PATH = path.join(__dirname, 'src', 'lib', 'trust.ts');

const GENERATED_CJS_PATH = path.join(
  __dirname,
  'src',
  'action',
  'trust.generated.cjs',
);

/**
 * Extract the string entries of an `export const NAME = [ ... ] as const;`
 * array literal from the trust.ts source. Deterministic and fail-loud: an
 * unfound literal (a renamed export) throws rather than silently emitting an
 * empty allowlist.
 */
function extractArrayLiteral(source, name) {
  const pattern = new RegExp(
    'export const ' + name + '\\s*=\\s*(\\[[^\\]]*\\])',
  );
  const match = source.match(pattern);

  if (match === null) {
    throw new Error(
      'selfcheck: could not find the ' + name + ' array literal in trust.ts',
    );
  }

  const entries = [];
  const stringPattern = /['"]([^'"]*)['"]/g;
  let stringMatch = stringPattern.exec(match[1]);

  while (stringMatch !== null) {
    entries.push(stringMatch[1]);
    stringMatch = stringPattern.exec(match[1]);
  }

  return entries;
}

function serializeArray(entries) {
  return '[' + entries.map((entry) => "'" + entry + "'").join(', ') + ']';
}

/**
 * Build the committed .cjs from a fixed CommonJS template embedding the two
 * extracted allowlists and reproducing hostSupportsWidenedTrust + isWriteTrusted
 * verbatim from trust.ts. Deterministic (idempotent): the same trust.ts always
 * yields byte-identical output. The banner marks it generated + prohibits hand
 * edits. LF line endings only (matched by .gitattributes eol=lf) so the byte
 * diff is stable across OSes.
 */
function generateTrustCjs() {
  const source = fs.readFileSync(TRUST_TS_PATH, 'utf8');
  const trustedEvents = extractArrayLiteral(source, 'TRUSTED_EVENTS');
  const hostGatedEvents = extractArrayLiteral(source, 'HOST_GATED_EVENTS');

  const lines = [
    '// GENERATED by packages/github-cache/selfcheck.cjs from src/lib/trust.ts.',
    '// DO NOT HAND-EDIT: run `node packages/github-cache/selfcheck.cjs --write`',
    '// to regenerate. selfcheck.cjs fails CI on any drift from trust.ts (D-07).',
    '//',
    '// Dependency-free CommonJS (node builtins only): a GitHub JS action runs this',
    '// write-start gate BEFORE `npm ci`, so it cannot import the compiled module.',
    "'use strict';",
    '',
    "const { URL } = require('node:url');",
    '',
    'const TRUSTED_EVENTS = ' + serializeArray(trustedEvents) + ';',
    '',
    'const HOST_GATED_EVENTS = ' + serializeArray(hostGatedEvents) + ';',
    '',
    'function hostSupportsWidenedTrust(env) {',
    "  const raw = env.GITHUB_SERVER_URL ?? '';",
    '  let host;',
    '',
    '  try {',
    '    host = new URL(raw).hostname.toLowerCase();',
    '  } catch {',
    '    return false;',
    '  }',
    '',
    "  return host === 'github.com' || host.endsWith('.ghe.com');",
    '}',
    '',
    'function isWriteTrusted(env) {',
    "  if (env.GITHUB_ACTIONS !== 'true') {",
    '    return false;',
    '  }',
    '',
    "  const event = env.GITHUB_EVENT_NAME ?? '';",
    '',
    '  if (TRUSTED_EVENTS.includes(event)) {',
    '    return true;',
    '  }',
    '',
    '  if (HOST_GATED_EVENTS.includes(event)) {',
    '    return hostSupportsWidenedTrust(env);',
    '  }',
    '',
    '  return false;',
    '}',
    '',
    'module.exports = { isWriteTrusted, TRUSTED_EVENTS, HOST_GATED_EVENTS };',
    '',
  ];

  return lines.join('\n');
}

if (require.main === module) {
  const generated = generateTrustCjs();

  if (process.argv.includes('--write')) {
    fs.writeFileSync(GENERATED_CJS_PATH, generated);
    process.stdout.write(
      'selfcheck: wrote ' +
        path.relative(process.cwd(), GENERATED_CJS_PATH) +
        '\n',
    );
    process.exit(0);
  }

  let committed;

  try {
    committed = fs.readFileSync(GENERATED_CJS_PATH, 'utf8');
  } catch {
    process.stderr.write(
      'selfcheck: DRIFT -- src/action/trust.generated.cjs is missing. ' +
        'Run `node packages/github-cache/selfcheck.cjs --write`.\n',
    );
    process.exit(1);
  }

  if (committed !== generated) {
    process.stderr.write(
      'selfcheck: DRIFT -- src/action/trust.generated.cjs is out of sync with ' +
        'src/lib/trust.ts. Regenerate with ' +
        '`node packages/github-cache/selfcheck.cjs --write` (never hand-edit the .cjs).\n',
    );
    process.exit(1);
  }

  process.stdout.write(
    'selfcheck: src/action/trust.generated.cjs is in sync with src/lib/trust.ts.\n',
  );
  process.exit(0);
}

module.exports = { generateTrustCjs };
